import type { Variety } from './types';

/**
 * The variety catalogue.
 *
 * Two rules this file follows, both of them mattering more than they look:
 *
 * 1. Every species listed is an established edible or a mushroom traditionally
 *    taken as a brew. Nothing here is a foraging guide. We never describe how
 *    to identify a mushroom in the wild, because a catalogue is the wrong place
 *    to learn that and getting it wrong is dangerous.
 * 2. Benefits are nutrition and culinary properties only. No claim that any
 *    mushroom prevents, treats or cures anything.
 */

export const varieties: Variety[] = [
  /* ---------------------------------------------------- always in stock */
  {
    slug: 'oyster',
    en: 'Oyster',
    bn: 'ওয়েস্টার মাশরুম',
    latin: 'Pleurotus ostreatus',
    group: 'fresh',
    availability: 'stocked',
    ownPhoto: true,
    blurb: 'Soft, quick and easy to like. If you have never cooked mushrooms, start here.',
    culinary: 'Tear it into strips and sear it hot. It picks up whatever you put with it, so garlic, soy, panch phoron, all of it works. Ready in about five minutes.',
    origin: 'Grown all over the world now, and widely across Bangladesh and India.',
    history: 'It got its name from the shape of the cap, not the taste. Farmers noticed it grows happily on straw and sawdust, which is why it became the everyday mushroom in so many countries.',
    benefits: ['শরীরের কোষকে সুরক্ষা দেয়', 'রক্তচাপ নিয়ন্ত্রণে সহায়তা করে', 'পাচনতন্ত্রের সুস্থতা বজায় রাখে'],
    chips: ['ZERO CHOLESTEROL', 'HIGH FIBRE', 'VITAMIN B3'],
  },
  {
    slug: 'button',
    en: 'Button',
    bn: 'বাটন মাশরুম',
    latin: 'Agaricus bisporus',
    group: 'fresh',
    availability: 'stocked',
    ownPhoto: true,
    blurb: 'The one everybody recognises. Mild, firm, and it goes with almost anything.',
    culinary: 'Slice and fry until the water cooks off and the edges go golden. Good in curry, good in pasta, good on toast.',
    origin: 'First grown commercially in France, now the most cultivated mushroom on earth.',
    history: 'Parisian growers worked out how to farm it in old quarries in the 1700s. That is why it was called the champignon de Paris for a long time.',
    benefits: ['শরীরের কোষকে সুরক্ষা দেয়', 'হরমোন উৎপাদনে ভূমিকা রাখে', 'শরীরের বিপাক ক্রিয়া বাড়ায়'],
    chips: ['LOW FAT', 'POTASSIUM', 'RIBOFLAVIN'],
  },
  {
    slug: 'enoki',
    en: 'Enoki',
    bn: 'এনোকি মাশরুম',
    latin: 'Flammulina filiformis',
    group: 'fresh',
    availability: 'stocked',
    ownPhoto: true,
    blurb: 'Long white threads with a gentle crunch. Lovely in soup and noodles.',
    culinary: 'Trim the base, then add it in the last thirty seconds so it keeps its bite. Wonderful in hot soup, ramen and hot pot.',
    origin: 'Cultivated mainly in East Asia, especially Japan, Korea and China.',
    history: 'The pale spindly enoki you buy is grown in the dark in cool rooms. Left in daylight the same fungus grows short and brown and looks like a different mushroom entirely.',
    benefits: ['শরীরের কোষকে সুরক্ষা দেয়', 'রক্তচাপ নিয়ন্ত্রণে সহায়তা করে', 'পাচনতন্ত্রের সুস্থতা বজায় রাখে'],
    chips: ['HIGH FIBRE', 'LOW-CALORIE', 'B VITAMINS'],
  },

  /* ------------------------------------------------------ gourmet fresh */
  {
    slug: 'shiitake',
    en: 'Shiitake',
    bn: 'শিটাকি মাশরুম',
    latin: 'Lentinula edodes',
    group: 'gourmet',
    availability: 'seasonal',
    ownPhoto: true,
    blurb: 'Deep and savoury, almost meaty. This is the one that converts people.',
    culinary: 'Take the stems off, they stay tough. Slice the caps thick and give them real heat. Dried shiitake soaked in warm water gives you both the mushroom and a very good stock.',
    origin: 'China and Japan, grown on hardwood logs for centuries.',
    history: 'Records of shiitake cultivation in China go back roughly a thousand years. Growers would cut notches in fallen logs and wait for the right spores to find them.',
    benefits: ['ত্বককে সুস্থ ও সতেজ রাখে', 'স্নায়ুতন্ত্রের কার্যকারিতা বজায় রাখে', 'শরীরের খনিজ ভারসাম্য রক্ষায় ভূমিকা রাখে'],
    chips: ['BETA-GLUCANS', 'NIACIN', 'UMAMI'],
  },
  {
    slug: 'king-oyster',
    en: 'King Oyster',
    bn: 'কিং ওয়েস্টার মাশরুম',
    latin: 'Pleurotus eryngii',
    group: 'gourmet',
    availability: 'seasonal',
    blurb: 'Thick white stems that slice like scallops and hold their shape in the pan.',
    culinary: 'Cut the stem into rounds, score the tops, and sear both sides in butter. It stays firm where other mushrooms go soft, so it works anywhere you want texture.',
    origin: 'Native around the Mediterranean and across Central Asia.',
    history: 'It grows on the roots of a thistle rather than on wood, which is unusual for an oyster mushroom and part of why the stem is so substantial.',
    benefits: ['উচ্চ প্রোটিন সমৃদ্ধ', 'কম ফ্যাট ও ক্যালোরি', 'পাচনতন্ত্রের জন্য ভালো'],
    chips: ['MEATY TEXTURE', 'HIGH PROTEIN', 'LOW FAT'],
  },
  {
    slug: 'pink-oyster',
    en: 'Pink Oyster',
    bn: 'পিংক ওয়েস্টার মাশরুম',
    latin: 'Pleurotus djamor',
    group: 'gourmet',
    availability: 'seasonal',
    blurb: 'A bright coral pink that fades as it cooks. Fast growing and a little smoky.',
    culinary: 'Fry it hard and dry. Cooked properly the strips go slightly chewy and taste faintly of bacon, which is why people use it in sandwiches.',
    origin: 'Tropical and subtropical regions, so it does well in our climate.',
    history: 'It likes the heat and fruits very quickly, sometimes in under two weeks, which makes it a favourite with small growers in warm countries.',
    benefits: ['উচ্চ ফাইবার সমৃদ্ধ', 'অ্যান্টিঅক্সিডেন্ট বহন করে', 'কম ক্যালোরি'],
    chips: ['HIGH FIBRE', 'FAST COOKING', 'ANTIOXIDANT'],
  },
  {
    slug: 'golden-oyster',
    en: 'Golden Oyster',
    bn: 'গোল্ডেন ওয়েস্টার মাশরুম',
    latin: 'Pleurotus citrinopileatus',
    group: 'gourmet',
    availability: 'seasonal',
    blurb: 'Clusters of small yellow caps with a nutty, slightly sharp flavour.',
    culinary: 'Delicate, so cook it briefly and season lightly. Beautiful scattered over rice or folded into eggs at the last moment.',
    origin: 'Eastern Russia, northern China and Japan.',
    history: 'The colour is real and it is stunning fresh, but it fades in the pan. Cooks often add it at the end partly to keep some of the gold on the plate.',
    benefits: ['ভিটামিন বি সমৃদ্ধ', 'কম ফ্যাট', 'শরীরের কোষকে সুরক্ষা দেয়'],
    chips: ['B VITAMINS', 'NUTTY', 'LOW FAT'],
  },
  {
    slug: 'shimeji',
    en: 'Shimeji',
    bn: 'শিমেজি মাশরুম',
    latin: 'Hypsizygus tessellatus',
    group: 'gourmet',
    availability: 'seasonal',
    blurb: 'Small brown caps on slim stems, sold in a tight bunch. Nutty once cooked.',
    culinary: 'Never eat it raw, it is bitter. That bitterness disappears completely with a few minutes of heat and turns into something sweet and nutty.',
    origin: 'Japan and across East Asia.',
    history: 'Sometimes sold as beech mushroom because it grows on beech wood. In Japan there is an old saying that pairs it with matsutake, one for aroma and one for flavour.',
    benefits: ['উচ্চ ফাইবার', 'কম ক্যালোরি', 'খনিজ পদার্থ সমৃদ্ধ'],
    chips: ['NUTTY', 'HIGH FIBRE', 'COOK FIRST'],
  },
  {
    slug: 'maitake',
    en: 'Maitake',
    bn: 'মাইতাকে মাশরুম',
    latin: 'Grifola frondosa',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Overlapping fronds in a big ruffled cluster. Rich and peppery.',
    culinary: 'Pull the cluster apart by hand and roast the pieces so the edges crisp. It takes high heat well and does not need much help.',
    origin: 'Temperate forests in Japan, China, Europe and North America.',
    history: 'The Japanese name means dancing mushroom. One story says foragers danced when they found one, because a good cluster can be enormous.',
    benefits: ['বিটা-গ্লুকান সমৃদ্ধ', 'কম ক্যালোরি', 'উচ্চ ফাইবার'],
    chips: ['BETA-GLUCANS', 'PEPPERY', 'ROASTS WELL'],
  },
  {
    slug: 'lionsmane',
    en: "Lion's Mane",
    bn: 'লায়ন্স মেন মাশরুম',
    latin: 'Hericium erinaceus',
    group: 'gourmet',
    availability: 'seasonal',
    ownPhoto: true,
    blurb: 'A shaggy white ball of soft spines. Pulls apart into strands like crab meat.',
    culinary: 'Tear it into thick pieces, press them flat in a hot dry pan, then finish with butter. The texture is the whole point, so do not chop it small.',
    origin: 'Hardwood forests across Asia, Europe and North America.',
    history: 'It has been used in Chinese cooking and in traditional preparations for a very long time, and has become popular again recently for its unusual texture.',
    benefits: ['স্নায়ুতন্ত্রের জন্য উপকারী', 'ঘুমের গুণগত মান উন্নত করে', 'স্ট্রেস কমাতে সহায়ক'],
    chips: ['ZERO CHOLESTEROL', 'HIGH FIBRE', 'SEAFOOD TEXTURE'],
  },
  {
    slug: 'milky',
    en: 'Milky',
    bn: 'মিল্কি মাশরুম',
    latin: 'Calocybe indica',
    group: 'fresh',
    availability: 'seasonal',
    ownPhoto: true,
    blurb: 'Big, white and built for our weather. It keeps better in the heat than most.',
    culinary: 'Firm and mild with a long shelf life. Very good in curry, where it holds together instead of collapsing.',
    origin: 'First described in West Bengal, and grown widely across South Asia.',
    history: 'This one is genuinely ours. It was identified in India and became a summer crop precisely because it tolerates the temperatures that stop other mushrooms fruiting.',
    benefits: ['ওজন নিয়ন্ত্রণে সহায়ক', 'হৃদপিণ্ডের স্বাস্থ্যের জন্য ভালো', 'রক্তে শর্করা নিয়ন্ত্রণে সাহায্য করে'],
    chips: ['SELENIUM', 'HEAT TOLERANT', 'LOW-CALORIE'],
  },
  {
    slug: 'paddy-straw',
    en: 'Paddy Straw',
    bn: 'খড় মাশরুম',
    latin: 'Volvariella volvacea',
    group: 'fresh',
    availability: 'order',
    blurb: 'Small and egg shaped, grown on rice straw. A staple across Asia.',
    culinary: 'Common in Chinese and Southeast Asian cooking, usually whole in soups and stir fries. Soft, quick and slightly earthy.',
    origin: 'East and Southeast Asia, grown on rice straw beds.',
    history: 'It is one of the most sensible mushrooms in the world for a rice growing country, because it turns the leftover straw from one crop into food.',
    benefits: ['প্রোটিন সমৃদ্ধ', 'কম ফ্যাট', 'দ্রুত রান্না হয়'],
    chips: ['PROTEIN', 'QUICK COOKING', 'GROWN ON STRAW'],
  },
  {
    slug: 'portobello',
    en: 'Portobello',
    bn: 'পোর্টোবেলো মাশরুম',
    latin: 'Agaricus bisporus',
    group: 'gourmet',
    availability: 'order',
    blurb: 'A button mushroom grown up. Wide, dark and deeply savoury.',
    culinary: 'Big enough to grill whole. Take the stem out, brush with oil, and cook it like a steak. The flavour is much stronger than the young ones.',
    origin: 'Same species as the button mushroom, simply left to mature.',
    history: 'Growers used to throw these away as overgrown. Someone gave them an Italian sounding name in the 1980s and they became a premium product almost overnight.',
    benefits: ['উচ্চ ফাইবার', 'পটাশিয়াম সমৃদ্ধ', 'কম ফ্যাট'],
    chips: ['GRILLS WHOLE', 'POTASSIUM', 'SAME AS BUTTON'],
  },
  {
    slug: 'cremini',
    en: 'Cremini',
    bn: 'ক্রেমিনি মাশরুম',
    latin: 'Agaricus bisporus',
    group: 'fresh',
    availability: 'order',
    blurb: 'The brown middle stage between button and portobello. Firmer and more flavourful.',
    culinary: 'Use it anywhere you would use a button mushroom when you want a bit more depth. It browns nicely and does not release as much water.',
    origin: 'Same species again, a brown strain picked young.',
    history: 'Button, cremini and portobello are one mushroom at three ages. Knowing that is genuinely useful when you are shopping, because the price gap is often larger than the difference.',
    benefits: ['শরীরের কোষকে সুরক্ষা দেয়', 'বিপাক ক্রিয়া বাড়ায়', 'কম ক্যালোরি'],
    chips: ['FIRM', 'RIBOFLAVIN', 'LOW-CALORIE'],
  },
  {
    slug: 'chestnut',
    en: 'Chestnut',
    bn: 'চেস্টনাট মাশরুম',
    latin: 'Pholiota adiposa',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Golden caps with a slight shine, growing in generous clusters.',
    culinary: 'Crisp stems and a sweet nutty cap. Good roasted, good in a broth, and it keeps its shape well.',
    origin: 'Asia and Europe, on hardwood.',
    history: 'The Latin name refers to the slightly greasy shine on young caps, which is a fair description if you have ever picked one up after rain.',
    benefits: ['ফাইবার সমৃদ্ধ', 'কম ফ্যাট', 'খনিজ পদার্থ বহন করে'],
    chips: ['SWEET', 'CRISP STEM', 'HIGH FIBRE'],
  },
  {
    slug: 'pioppino',
    en: 'Pioppino',
    bn: 'পিওপ্পিনো মাশরুম',
    latin: 'Cyclocybe aegerita',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Slim stems, dark caps, and a properly wild woody flavour.',
    culinary: 'A favourite in Italian kitchens. Excellent slow cooked with tomato and garlic, where the stems stay pleasantly firm.',
    origin: 'Southern Europe, traditionally on poplar wood.',
    history: 'Named after the poplar tree it grows on. It is one of the older cultivated mushrooms in Europe, farmed on logs long before modern growing rooms existed.',
    benefits: ['প্রোটিন সমৃদ্ধ', 'উচ্চ ফাইবার', 'কম ক্যালোরি'],
    chips: ['WOODY', 'PROTEIN', 'SLOW COOKS WELL'],
  },
  {
    slug: 'velvet-shank',
    en: 'Velvet Shank',
    bn: 'ভেলভেট শ্যাংক',
    latin: 'Flammulina velutipes',
    group: 'gourmet',
    availability: 'order',
    blurb: 'The wild cousin of enoki, and it looks nothing like it. Orange caps, dark velvety stems.',
    culinary: 'Sticky caps and a gentle flavour that suits soup. The stems are tougher than cultivated enoki, so give them longer.',
    origin: 'Temperate forests across the northern hemisphere.',
    history: 'Grow the same family in the dark and you get pale enoki threads. Grow it in daylight on wood and you get this. It is a good reminder of how much conditions change a mushroom.',
    benefits: ['কম ক্যালোরি', 'ফাইবার সমৃদ্ধ', 'ভিটামিন বি বহন করে'],
    chips: ['WILD FORM', 'SOUPS', 'LOW-CALORIE'],
  },
  {
    slug: 'shaggy-mane',
    en: 'Shaggy Mane',
    bn: 'শ্যাগি মেন মাশরুম',
    latin: 'Coprinus comatus',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Tall white columns with shaggy scales. Delicate, and it does not wait around.',
    culinary: 'Cook it the day you get it. Very soft, almost creamy, and best treated simply in butter or in a light soup.',
    origin: 'Grasslands across Europe, Asia and North America.',
    history: 'It has a short life by design. Within a day or two the cap dissolves into a black ink, which people once actually used for writing.',
    benefits: ['কম ক্যালোরি', 'ফাইবার সমৃদ্ধ', 'দ্রুত রান্নার উপযোগী'],
    chips: ['VERY PERISHABLE', 'DELICATE', 'COOK SAME DAY'],
  },
  {
    slug: 'chanterelle',
    en: 'Chanterelle',
    bn: 'শ্যান্টেরেল মাশরুম',
    latin: 'Cantharellus cibarius',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Golden and trumpet shaped, with a faint smell of apricot.',
    culinary: 'Dry fry first to drive the water off, then butter. Do not drown it in strong spice, the flavour is the reason you bought it.',
    origin: 'Forests across Europe, Asia and North America.',
    history: 'Nobody has managed to farm it properly. Chanterelles need a living tree to partner with, so every one on the market has been picked by hand.',
    benefits: ['ভিটামিন ডি বহন করে', 'কম ক্যালোরি', 'খনিজ সমৃদ্ধ'],
    chips: ['WILD PICKED', 'VITAMIN D', 'APRICOT AROMA'],
  },
  {
    slug: 'porcini',
    en: 'Porcini',
    bn: 'পোরচিনি মাশরুম',
    latin: 'Boletus edulis',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Fat brown caps and thick stems. One of the great cooking mushrooms.',
    culinary: 'Fresh is a treat. Dried is a workhorse, and a small handful soaked in warm water will lift an entire pot of rice or soup.',
    origin: 'Europe originally, now found across the northern hemisphere.',
    history: 'The Italian name means piglets. Like chanterelle it partners with tree roots and resists farming, which is why good porcini has never been cheap.',
    benefits: ['প্রোটিন সমৃদ্ধ', 'ফাইবার সমৃদ্ধ', 'খনিজ পদার্থ বহন করে'],
    chips: ['WILD PICKED', 'PROTEIN', 'GREAT DRIED'],
  },
  {
    slug: 'morel',
    en: 'Morel',
    bn: 'মোরেল মাশরুম / গুচ্ছি',
    latin: 'Morchella esculenta',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Honeycomb caps and a flavour people plan their year around.',
    culinary: 'Always cook morels thoroughly, never raw. Once cooked they are nutty and deep, and the hollow inside is made for stuffing.',
    origin: 'Temperate forests, and in South Asia especially the Himalayan belt.',
    history: 'In Kashmir and Himachal it is called guchhi and is one of the most expensive foods in the region, because it appears briefly in spring and refuses to be farmed.',
    benefits: ['আয়রন সমৃদ্ধ', 'ভিটামিন ডি বহন করে', 'কম ফ্যাট'],
    chips: ['COOK THOROUGHLY', 'IRON', 'SPRING ONLY'],
  },
  {
    slug: 'black-trumpet',
    en: 'Black Trumpet',
    bn: 'ব্ল্যাক ট্রাম্পেট',
    latin: 'Craterellus cornucopioides',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Thin dark funnels that look like nothing and taste like a great deal.',
    culinary: 'Strong and smoky, a little goes a long way. Very good dried and crushed into a powder to season with.',
    origin: 'Woodland across Europe, Asia and North America.',
    history: 'It is nearly invisible against dark leaf litter, which has earned it some gloomy nicknames over the years despite being excellent to eat.',
    benefits: ['কম ক্যালোরি', 'খনিজ সমৃদ্ধ', 'শক্তিশালী স্বাদ'],
    chips: ['SMOKY', 'GREAT DRIED', 'LOW-CALORIE'],
  },
  {
    slug: 'hedgehog',
    en: 'Hedgehog',
    bn: 'হেজহগ মাশরুম',
    latin: 'Hydnum repandum',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Cream coloured, with soft spines underneath instead of gills.',
    culinary: 'Firm, slightly sweet, and it holds up to a long cook. Slightly peppery when older, which butter sorts out.',
    origin: 'Woodland across Europe and North America.',
    history: 'The spines under the cap are the giveaway and the reason for the name. It is one of the sturdier wild mushrooms and travels better than most.',
    benefits: ['ফাইবার সমৃদ্ধ', 'কম ফ্যাট', 'খনিজ পদার্থ বহন করে'],
    chips: ['FIRM', 'SLIGHTLY SWEET', 'HIGH FIBRE'],
  },
  {
    slug: 'matsutake',
    en: 'Matsutake',
    bn: 'মাতসুতাকে মাশরুম',
    latin: 'Tricholoma matsutake',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Famous for its smell more than its taste. Spicy, piney, unmistakable.',
    culinary: 'Do as little as possible. Traditionally it is torn by hand and cooked in a clear broth or rice so the aroma carries.',
    origin: 'Pine forests in Japan, Korea, China and parts of North America.',
    history: 'It is tied to the health of particular pine forests, and as those forests declined so did the harvest. That scarcity is why a good one can cost more than almost any other mushroom.',
    benefits: ['প্রোটিন সমৃদ্ধ', 'কম ফ্যাট', 'স্বতন্ত্র সুগন্ধ'],
    chips: ['RARE', 'AROMATIC', 'MINIMAL COOKING'],
  },
  {
    slug: 'truffle',
    en: 'Black Truffle',
    bn: 'ব্ল্যাক ট্রাফল',
    latin: 'Tuber melanosporum',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Grows underground, found by dogs, shaved over food at the last second.',
    culinary: 'Never cook it hard. Shave it raw over something warm and fatty, like eggs, butter rice or pasta, and let the heat carry the smell.',
    origin: 'Southern Europe, especially France, Spain and Italy.',
    history: 'Because it fruits underground it cannot spread spores by air, so it evolved a powerful smell to get animals to dig it up. Dogs are trained for it now, pigs used to be.',
    benefits: ['স্বতন্ত্র সুগন্ধ', 'কম ক্যালোরি', 'অল্প পরিমাণেই যথেষ্ট'],
    chips: ['SHAVE RAW', 'INTENSE AROMA', 'A LITTLE GOES FAR'],
  },
  {
    slug: 'almond',
    en: 'Almond Mushroom',
    bn: 'আলমন্ড মাশরুম',
    latin: 'Agaricus subrufescens',
    group: 'gourmet',
    availability: 'order',
    blurb: 'A close relative of the button mushroom that genuinely smells of almonds.',
    culinary: 'Sweet and mild. Lovely simply pan fried, and the almond note survives cooking better than you would expect.',
    origin: 'Brazil and North America, now grown in Asia too.',
    history: 'It became widely known after being studied and farmed in Brazil and Japan, and is often sold under a handful of different regional names.',
    benefits: ['প্রোটিন সমৃদ্ধ', 'ফাইবার সমৃদ্ধ', 'কম ফ্যাট'],
    chips: ['SWEET', 'ALMOND AROMA', 'PROTEIN'],
  },
  {
    slug: 'saffron-milkcap',
    en: 'Saffron Milk Cap',
    bn: 'স্যাফরন মিল্ক ক্যাপ',
    latin: 'Lactarius deliciosus',
    group: 'gourmet',
    availability: 'order',
    blurb: 'Orange, faintly green where handled, and firm enough to grill.',
    culinary: 'Grill or roast it whole with oil and salt. It stays firm and slightly crunchy, which is unusual and very good.',
    origin: 'Pine forests around the Mediterranean and now much further afield.',
    history: 'It appears in Roman era wall paintings, which makes it one of the few mushrooms we can prove people were eating two thousand years ago.',
    benefits: ['ভিটামিন বি সমৃদ্ধ', 'খনিজ পদার্থ বহন করে', 'কম ক্যালোরি'],
    chips: ['GRILLS WELL', 'FIRM', 'B VITAMINS'],
  },

  /* ------------------------------------------------- wellness and brews */
  {
    slug: 'reishi',
    en: 'Reishi',
    bn: 'রেইশি / গ্যানোডার্মা',
    latin: 'Ganoderma lucidum',
    group: 'wellness',
    availability: 'seasonal',
    ownPhoto: true,
    blurb: 'Woody and bitter. This one is brewed, not fried.',
    culinary: 'Slice it thin and simmer for an hour or more to make a dark bitter tea. Honey or ginger helps if the bitterness is new to you.',
    origin: 'Hardwood forests across Asia.',
    history: 'It appears in Chinese art and writing going back two thousand years, usually as a symbol of long life. The polished red surface is why it was often carved and kept rather than eaten.',
    benefits: ['অ্যান্টিঅক্সিডেন্টে ভরপুর', 'ঐতিহ্যবাহী ভেষজ চা হিসেবে ব্যবহৃত', 'ক্যাফেইন মুক্ত'],
    chips: ['BREW ONLY', 'ANTIOXIDANT', 'CAFFEINE FREE'],
  },
  {
    slug: 'chaga',
    en: 'Chaga',
    bn: 'চাগা',
    latin: 'Inonotus obliquus',
    group: 'wellness',
    availability: 'order',
    blurb: 'A hard black mass that grows on birch. Brewed as a dark earthy tea.',
    culinary: 'Break off small pieces and simmer gently for a long time. The result is dark and mild with a faint vanilla edge, and it reheats well.',
    origin: 'Birch forests in northern Russia, Scandinavia, Korea and Canada.',
    history: 'It has been brewed in Siberia and northern Europe for generations, mostly as a warm drink through long winters.',
    benefits: ['অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ', 'ক্যাফেইন মুক্ত পানীয়', 'ঐতিহ্যবাহী শীতকালীন চা'],
    chips: ['BREW ONLY', 'ANTIOXIDANT', 'EARTHY'],
  },
  {
    slug: 'cordyceps',
    en: 'Cordyceps',
    bn: 'কর্ডিসেপস',
    latin: 'Cordyceps militaris',
    group: 'wellness',
    availability: 'order',
    blurb: 'Small orange clubs, usually taken as a tea or a powder.',
    culinary: 'Steep a few pieces in hot water for a mild, slightly sweet drink. Some people add it to broth or a morning smoothie.',
    origin: 'Grown commercially across East Asia.',
    history: 'The cultivated orange kind you see today is farmed on grain in clean rooms, which is what made it affordable. The wild relative it is named after was always rare.',
    benefits: ['ঐতিহ্যবাহী টনিক হিসেবে ব্যবহৃত', 'ক্যাফেইন মুক্ত', 'অ্যান্টিঅক্সিডেন্ট বহন করে'],
    chips: ['TEA OR POWDER', 'CAFFEINE FREE', 'CULTIVATED'],
  },
  {
    slug: 'turkey-tail',
    en: 'Turkey Tail',
    bn: 'টার্কি টেইল',
    latin: 'Trametes versicolor',
    group: 'wellness',
    availability: 'order',
    blurb: 'Thin banded fans in rings of brown and grey. Too tough to chew, so it is brewed.',
    culinary: 'Simmer the fans for a long time and drink the liquid. Mild and woody, and it takes ginger or cinnamon happily.',
    origin: 'Found on dead wood almost everywhere in the world.',
    history: 'It is probably the most common shelf fungus on earth, and it has been used as a simmered drink in Chinese and Japanese practice for centuries.',
    benefits: ['বিটা-গ্লুকান বহন করে', 'ক্যাফেইন মুক্ত পানীয়', 'ঐতিহ্যবাহী ব্যবহার'],
    chips: ['BREW ONLY', 'BETA-GLUCANS', 'WOODY'],
  },
  {
    slug: 'tremella',
    en: 'Snow Fungus',
    bn: 'স্নো ফাংগাস',
    latin: 'Tremella fuciformis',
    group: 'wellness',
    availability: 'order',
    blurb: 'Translucent white frills. Almost no flavour, wonderful texture.',
    culinary: 'Soak it, then simmer with rock sugar and dried fruit for a classic sweet soup. It goes soft and slippery and soaks up whatever it is cooked in.',
    origin: 'Tropical and subtropical forests, widely grown in China.',
    history: 'It has been a dessert ingredient in China for a very long time and was once reserved for the wealthy, before cultivation made it ordinary.',
    benefits: ['উচ্চ ফাইবার', 'কম ক্যালোরি', 'মিষ্টি স্যুপে ব্যবহৃত'],
    chips: ['DESSERT SOUP', 'HIGH FIBRE', 'LOW-CALORIE'],
  },
  {
    slug: 'woodear',
    en: 'Wood Ear',
    bn: 'উড ইয়ার মাশরুম',
    latin: 'Auricularia auricula-judae',
    group: 'fresh',
    availability: 'seasonal',
    ownPhoto: true,
    blurb: 'All texture and very little flavour, which is exactly the point.',
    culinary: 'Sold dried. Soak it and it swells into something with a proper bounce. Slice it thin into hot and sour soup or a stir fry.',
    origin: 'Grown across China and Southeast Asia, found worldwide.',
    history: 'It is one of the oldest cultivated mushrooms anywhere, with Chinese growing records going back well over a thousand years.',
    benefits: ['রক্তনালী নরম ও নমনীয় রাখে', 'কোষ্ঠকাঠিন্য দূর করে', 'ডায়াবেটিক-ফ্রেন্ডলি খাদ্যতালিকার জন্য উপযোগী'],
    chips: ['HIGH FIBRE', 'IRON', 'SOLD DRIED'],
  },
];

export const bySlug = (slug: string) => varieties.find((v) => v.slug === slug);

/** The three we always have. Everything else is seasonal or brought in to order. */
export const stocked = varieties.filter((v) => v.availability === 'stocked');

export const groups = [
  { id: 'fresh', label: 'Everyday fresh', bn: 'প্রতিদিনের তাজা' },
  { id: 'gourmet', label: 'Gourmet & specialty', bn: 'বিশেষ জাত' },
  { id: 'wellness', label: 'Wellness & brewing', bn: 'ওয়েলনেস ও চা' },
] as const;

export function imageFor(v: Variety) {
  return v.ownPhoto ? `/assets/tiles/${v.slug}.webp` : `/assets/species/${v.slug}.webp`;
}
